CREATE TABLE TBL_AUTHOR (
    AUTHOR_ID INT PRIMARY KEY,
    AUTHOR_NAME VARCHAR(10),
    COUNTRY VARCHAR(10)
);

CREATE TABLE TBL_BOOK (
    BOOK_ID INT PRIMARY KEY,
    BOOK_TITLE VARCHAR(10),
    AUHTORID INT,
    FOREIGN KEY (AUHTORID) REFERENCES TBL_AUTHOR(AUTHOR_ID)
);


INSERT INTO TBL_AUTHOR VALUES
(1, 'CHETAN', 'India'),
(2, 'JONNY', 'USA'),
(3, 'SHIN', 'China');


INSERT INTO TBL_BOOK VALUES
(101, 'SQL101', 1),
(102, 'NoSQL', 2),
(103, 'DBMS', 3);


SELECT B.BOOK_TITLE, A.AUTHOR_NAME, A.COUNTRY
FROM TBL_BOOK AS B
INNER JOIN TBL_AUTHOR AS A
ON B.AUHTORID = A.AUTHOR_ID;
